/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ramapkri' at '12/29/15 11:35 AM' with Gradle 2.5-rc-2
 *
 * @author ramapkri, @date 12/29/15 11:35 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
